# Generated by Django 2.2.12 on 2020-05-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0003_auto_20200513_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lenguaje', models.CharField(max_length=50, verbose_name='Lenguaje')),
                ('MotorDB', models.CharField(max_length=155, verbose_name='Motor de Base De Datos')),
                ('Arquitectura', models.CharField(max_length=255, verbose_name='Arquitectura')),
            ],
            options={
                'verbose_name': 'Categoria del Proyecto',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTiDoc', models.CharField(max_length=45, verbose_name='Nombre Tipo Documento')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombProy', models.TextField(verbose_name='Nombre Del Proyecto')),
                ('ImgProye', models.ImageField(default='user.png', upload_to='', verbose_name='Foto de perfil')),
                ('FechaIni', models.DateTimeField(auto_now_add=True)),
                ('FechaFin', models.DateTimeField(auto_now_add=True)),
                ('UrlRepo', models.TextField(verbose_name='Url del Repositorio')),
                ('EstaProy', models.CharField(max_length=45, verbose_name='Estado del Proyecto')),
                ('idCategProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombDocu', models.CharField(max_length=50, verbose_name='Nombre Del Documento')),
                ('PathDocu', models.CharField(max_length=50, verbose_name='Ruta de Almacenamiento del Documento')),
                ('idProyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
